# Copyright 2020 Alfredo de la fuente - AvanzOSC
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    "name": "Product Make",
    "version": "16.0.1.0.0",
    "category": "Sales/Sales",
    "license": "AGPL-3",
    "author": "AvanzOSC",
    "website": "https://github.com/avanzosc/odoo-addons",
    "depends": [
        "product",
        "sale_management",
        "sales_team",
        "contacts",
        "account",
        "stock",
        "partner_group_purchase",
        "sale_order_line_sequence",
        "delivery",
        "delivery_auto_refresh",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/product_make_groups.xml",
        "views/res_partner_relation_views.xml",
        "views/res_partner_classification_views.xml",
        "views/product_make_views.xml",
        "views/product_template_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/account_move_line_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_move_views.xml",
        "views/make_amount_views.xml",
        "views/res_partner_market_views.xml",
        "views/res_partner_market_sector_views.xml",
        "views/res_users_views.xml",
        "reports/report_res_partner_make_amount.xml",
        "reports/sale_report_views.xml",
    ],
    "installable": True,
    "post_init_hook": "_put_sale_info_in_invoices",
}
