# Copyright 2017 Tecnativa - Vicent Cubells
# Copyright 2018 Tecnativa - Carlos Dauden
# Copyright 2017-2018 Tecnativa - Pedro M. Baeza
# Copyright 2025 Alfredo de la Fuente - AvanzOSC
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "SPACORP Custom",
    "version": "16.0.1.0.0",
    "author": "Tecnativa & AvanzOSC",
    "website": "https://github.com/avanzosc/odoo-addons",
    "license": "AGPL-3",
    "category": "Others",
    "depends": [
        "l10n_es",
        "sale_stock",
        "sale_order_type",
        "contacts",
        "account",
        "sale_crm",
        "sale_commission",
        "product_pricelist_item_menu",
        "web_tree_dynamic_colored_field",
        "purchase",
        "delivery",
        "sale_commission",
        "mail",
        "mrp",
        "project",
        "account_payment_order",
        "mrp_production_cost",
        "sales_team",
        "account_invoice_fiscal_position_update",
        "account_tax_balance",
        "sale_global_discount",
        "stock_picking_report_valued",
        "product_make",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/account_tax_group_data.xml",
        "data/account_template_data.xml",
        "data/taxes_data.xml",
        "data/fiscal_position_data.xml",
        "data/spacorp_custom.xml",
        "data/mail_template.xml",
        "views/product_make_views.xml",
        "views/res_partner_market_views.xml",
        "views/res_partner_market_sector_views.xml",
        "views/stock_picking_shipping_type_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_warehouse_views.xml",
        "views/sale_order_type_views.xml",
        "views/account_invoice_views.xml",
        "views/product_pricelist_views.xml",
        "views/product_pricelist_item_views.xml",
        "views/product_template_view.xml",
        "views/product_product_view.xml",
        "views/res_config_settings_views.xml",
        "views/stock_move_views.xml",
        "views/sale_order_line_agent_view.xml",
        "views/res_users_views.xml",
        "views/project_task_views.xml",
        "views/crm_team_views.xml",
        "views/account_fiscal_position_views.xml",
        "views/account_move_views.xml",
        "views/mrp_production_views.xml",
        "reports/common.xml",
        "reports/account_invoice_report_view.xml",
        "reports/report_sale.xml",
        "reports/report_sale_labels.xml",
        "reports/report_stockpicking_operations.xml",
        "reports/report_stock_picking.xml",
        "reports/report_invoice.xml",
    ],
    "installable": True,
}
