from . import res_partner_market
from . import res_partner_market_sector
from . import res_partner
from . import product_make
from . import make_amount
from . import res_partner_make_saleperson
from . import res_partner_relation
from . import res_partner_classification
from . import product_template
from . import sale_order_line
from . import sale_order
from . import account_move
from . import account_move_line
from . import stock_move
from . import stock_picking
from . import crm_team
from . import res_users
