from . import stock_warehouse
from . import res_partner
from . import category_type
from . import product_category
from . import product_template
from . import stock_move_line
from . import stock_move
from . import stock_picking_type
from . import stock_picking
