from . import stock_picking_type
from . import category_type
from . import picking_batch_stage
from . import stock_warehouse
from . import res_partner
from . import product_category
from . import product_template
from . import stock_move_line
from . import stock_move
from . import stock_picking
from . import stock_picking_batch
from . import stock_location
from . import stock_quant
