from . import sale_order
from . import sale_order_line
from . import product_pricelist_item
from . import stock_picking
from . import purchase_order
from . import purchase_order_line
from . import res_partner
from . import stock_inventory
from . import account_move_line
from . import stock_move_line
