from . import stock_warehouse
from . import move_type
from . import liquidation_line
from . import liquidation_contract
from . import liquidation_contract_line
from . import product_category
from . import account_move
from . import stock_picking_batch
from . import stock_inventory
from . import stock_inventory_line
from . import account_move_line
from . import feed_rate
from . import stock_move
from . import stock_move_line
from . import product_template
from . import account_analytic_line
