from . import fleet_vehicle_classification
from . import fleet_vehicle_variant
from . import fleet_vehicle_version
from . import fleet_vehicle_category
from . import fleet_vehicle_mmta
from . import fleet_vehicle_mma
from . import fleet_vehicle_service_brake_type
from . import fleet_vehicle_tire_dimension
from . import fleet_vehicle_ic_iv_tire
from . import fleet_vehicle
