# Copyright 2024 Berezi Amubieta - AvanzOSC
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).

{
    "name": "Custom P",
    "version": "14.0.1.0.0",
    "category": "Custom",
    "license": "AGPL-3",
    "author": "AvanzOSC",
    "website": "https://github.com/avanzosc/odoo-addons",
    "depends": [
        "product",
        "sale_stock",
        "sale_order_return",
        "sale_order_line_price_history",
        "sale_order_lot_selection",
        "sale_order_lot_selection_domain",
        "sale_order_line_commitment_date",
        "account",
        "stock_picking_cmr_report",
        "product_pricelist_direct_print_fix",
        "purchase",
        "stock_warehouse_farm",
        "res_partner_risk_menu",
        "purchase_order_return",
        "sale_order_usability",
        "sale_order_line_gross_weight",
        "custom_breeding_apps",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/picking_unlock_groups.xml",
        "views/sale_order_view.xml",
        "views/sale_order_line_view.xml",
        "views/account_move_view.xml",
        "views/product_pricelist_item_view.xml",
        "views/purchase_order_line_view.xml",
        "views/res_partner_view.xml",
        "views/account_invoice_report_view.xml",
        "views/stock_picking_view.xml",
        "views/product_packaging_view.xml",
        "views/hr_employee_view.xml",
        "wizards/sale_order_line_price_history_view.xml",
        "wizards/stock_inventory_warning_wizard_view.xml",
    ],
    "installable": True,
}
