from . import chassis
from . import screen_size
from . import resolution
from . import processor
from . import speed
from . import gen
from . import ram
from . import storage_size
from . import storage_type
from . import keyboard
from . import software_license_key
from . import grade
from . import ram_type
from . import battery_model
from . import lot_component
from . import stock_production_lot
from . import product_model
